# provided at command line action=XXX where XXX can be create_user
action: ''
account_email:
user_key_path:
ca_dir_url: "http://192.168.99.100:4000/directory"
maradns_config_file: /etc/maradns/maradns.org
# coma sep list of domain, first one is the principle one
domain:
# If not exists it will be generated first time
private_key_path: server-{{ env }}.key
public_key_path: server-{{ env }}.crt